BilgeadamHomework/Models/EntityFramework/Departman.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgeadamHomework.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departman()
        {
            this.Personel = new HashSet<Personel>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personel> Personel { get; set; }
    }
}

BilgeadamHomework/Controllers/DepartmanController.cs
using BilgeadamHomework.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BilgeadamHomework.Controllers
{
    
    public class DepartmanController : Controller
    {
        PersonelDbEntities db = new PersonelDbEntities();
        
        public ActionResult Index()//İlk açılış ekranı. Tüm departmanlar gösterilecek.
        {
            var model= db.Departman.ToList();//Deprtman tablosunu listeye çevirdim.
            return View(model);//Listeyi viewe gönderdim.
        }
        [HttpGet]//Default değer.
        [Authorize(Roles = "A")]
        public ActionResult Yeni()//Yeni Departman için boş form gönderir. 
        {
            return View("DepartmanForm",new Departman());
        }
        //[HttpPost]Post durumunda bu aksiyon çalışsın.Antiforgery için pasife aldım.
        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Departman departman)//Yeni departman formundan dönen bilgiyi db'e kaydeder. 
        {
            if (!ModelState.IsValid)//server side Validation
            {
                return View("DepartmanForm");
            } 
            if (departman.Id==0)//id=0 ise yeni ekleme kaydı
            {
                db.Departman.Add(departman);
            }else//id!=0 ise güncelleme kaydı
            {
                var guncellenecekDepartman = db.Departman.Find(departman.Id);
                if (guncellenecekDepartman==null)
                {
                    return HttpNotFound();
                }
                guncellenecekDepartman.Ad = departman.Ad;
            }
            db.SaveChanges();
            return RedirectToAction("Index","Departman");
        }
       
        public ActionResult Guncelle(int Id)//argüman olarak Id alacak.DepartmanForm view'i ortak kullanılabilir. 
        {
            var model = db.Departman.Find(Id);
            if (model == null)
                return HttpNotFound();
            return View("DepartmanForm",model);//Güncelle view yerine DepartmanForm view'e gönder.
        }
        public ActionResult Sil(int Id)
        {
            var silinecek = db.Departman.Find(Id);
            if (silinecek==null)
            {
                return HttpNotFound();
            }
            db.Departman.Remove(silinecek);
            db.SaveChanges();
            return RedirectToAction("Index","Departman");
        }
    }
}

BilgeadamHomework/Controllers/PersonelController.cs
using BilgeadamHomework.Models.EntityFramework;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BilgeadamHomework.ViewModels;

namespace BilgeadamHomework.Controllers
{
    [Authorize]
    public class PersonelController : Controller
    {
        PersonelDbEntities db = new PersonelDbEntities();
        
        public ActionResult Index()
        {
            var model = db.Personel.Include(x=>x.Departman).ToList();
            return View(model);
        }
        [Authorize(Roles ="A")]
        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel=new Personel()
            };
            return View("PersonelForm",model);
        }
        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            if (!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm",model);
            }
            if (personel.Id==0)
            {
                db.Personel.Add(personel);//Yeni personel ekle işlemi
            }
            else//Güncelleme
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;//Tek satırda bütün bilgileri günceller.
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle(int Id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(Id)
        };
            return View("PersonelForm",model);
        }

        public ActionResult Sil(int Id)
        {
            var silinecekPersonel = db.Personel.Find(Id);
            if (silinecekPersonel==null)
            {
                return HttpNotFound();
            }
            db.Personel.Remove(silinecekPersonel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelleriListele(int id)
        {
            var model = db.Personel.Where(x=>x.Id==id).ToList();
            return PartialView(model);
        }
    }
}

BilgeadamHomework/Views/Departman/DepartmanForm.cshtml
@model BilgeadamHomework.Models.EntityFramework.Departman
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Kaydet", "Departman", FormMethod.Post))//action ve metodu oluşturur.
{
    @Html.AntiForgeryToken()@*Author. kontrolü*@
    <div class="form-group">
        @Html.LabelFor(m => m.Ad) @*modeldeki ada göre oluştur.*@
        @Html.TextBoxFor(m => m.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ad)
    </div>
    @Html.HiddenFor(m => m.Id);
    <button type="submit" class="btn btn-success">Kaydet</button>
}

@section scripts
    {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}@*Bu alan, layoutta renderscript alanına gidecek.*@

BilgeadamHomework/Views/Departman/Index.cshtml
@using BilgeadamHomework.Models.EntityFramework
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (User.IsInRole("A"))
{
    <a class="btn btn-success" href="/Departman/Yeni">Yeni Departman</a>
}
    <h2>Departmanlar Listesi</h2>
    <br />
    <table class="table table-bordered" id="tblDepartmanlar">
        <thead>
            <tr>
                <th>ID</th>
                <th>Ad</th>
                <th>Güncelle</th>
                <th>Sil</th>
                <th>Personeller</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var departman in Model)
            {
            <tr>
                <td>@departman.Id</td>
                <td>@departman.Ad</td>
                <td><a class="btn btn-primary" href="/Departman/Guncelle/@departman.Id">Güncelle</a></td>

                <td><a class="btn btn-warning" href="/Departman/Sil/@departman.Id">Sil</a></td>
                
                <td>@Ajax.ActionLink("Personelleri Göster", "PersonelleriListele", "Personel", new { id = departman.Id }, new AjaxOptions{HttpMethod="GET",UpdateTargetId="personelListesi"}, new { @class="btn btn-primary"})</td>
            </tr>
            }

        </tbody>
    </table>
<div id="personelListesi"></div>